version: 2.1
orbs:
  python: circleci/python@1.4.0
  aws-cli: circleci/aws-cli@1.2.1

executors:
  python-linter:
    docker:
      - image: cimg/python:3.8

jobs:
  build-and-test:
    executor: python-linter
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Create ENV
          command: env > .env
      - run:
          name: Run tests
          command: python -m pytest

  build_and_publish:
    executor: python-linter
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Setup Virtual env
          command: |
            virtualenv -p python3.8 env            
            echo "source ./env/bin/activate" >> $BASH_ENV
      - run:
          name: Create ENV
          command: env > .env
      - run: python -m site
      - run:
          name: Create Zipfile archive of Dependencies
          command: |
            cd env/lib/python3.8/site-packages
            zip -r9 ../../../../function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip .env -r app
      - run: ls
      - persist_to_workspace:
          root: .
          paths:
            - function.zip

  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Upload to S3
          command: aws s3 cp function.zip s3://tumtpk/function.zip
      - run:
          name: Deploy new Lambda
          command: aws lambda update-function-code --function-name tumtpk --s3-bucket tumtpk --s3-key function.zip

workflows:
  my-workflow:
    jobs:
      - build-and-test:
          context:
            - lab_test06
      - build_and_publish:
          context:
            - lab_test06
          requires:
            - build-and-test
      - deploy:
          context:
            - aws_lab06
          requires:
            - build_and_publish
          filters:
            branches:
              only:
                - main
