version: 2.1
orbs:
  python: circleci/python@1.4.0
  aws-cli: circleci/aws-cli@1.2.1

executors:
  python-linter:
    docker:
      - image: cimg/python:3.8

jobs:
  build-and-test:
    executor: python-linter
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Create ENV
          command: env > .env
      - run:
          name: Run tests
          command: python -m pytest

  build_and_publish:
    executor: python-linter
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Create ENV
          command: env > .env
      - run: python -m site
      # - run:
      #     name: Create Zipfile archive of Dependencies
      #     command: |
      #       cd /home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages
      #       zip -r9 /home/function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip -r ./
      - persist_to_workspace:
          root: .
          paths:
            - function.zip

  # deploy:
  #   executor: gcp-cli/default
  #   steps:
  #     - gcp-cli/install
  #     - gcp-cli/initialize
  #     - run:
  #         name: deploy service
  #         command: |
  #           export cmd='sudo docker stop $(docker ps -a -q) || true && sudo docker rm $(docker ps -a -q) || true && docker image prune -a -f || true && docker run -d -p 80:8000'
  #           gcloud --quiet compute ssh  "$GCE_INSTANCE_NAME" --tunnel-through-iap --command="$cmd $IMAGE_NAME"

workflows:
  my-workflow:
    jobs:
      - build-and-test:
          context:
            - lab_test06
      - build_and_publish:
          context:
            - lab_test06
          requires:
            - build-and-test
      #  - deploy:
      #     requires:
      #       - build_and_publish
