version: 2.1
orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |
            virtualenv -p python3.8 env            
            echo "source ./env/bin/activate" >> $BASH_ENV
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Create ENV
          command: env > .env
      - run: echo ${USER_NAME}
      - run:
          name: Run tests
          command: python -m pytest
