version: 2.1
orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          command:
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -\
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list\
            apt-get update \
            apt-get install -y mongodb-org=4.4.13 mongodb-org-server=4.4.13 mongodb-org-shell=4.4.13 mongodb-org-mongos=4.4.13 mongodb-org-tools=4.4.13\
            systemctl start mongod
      - run:
          name: create user
          command: mongodb && mongo --eval 'db.createUser({ "user":"root", "pwd":"root", "roles":[ { "role":"userAdminAnyDatabase", "db":"admin" } ] })'
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Run tests
          command: python -m pytest
