version: 2.1
orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
      - image: circleci/mongo:4.2.0

    steps:
      - checkout
      - run:
          name: MongoDB Install
          command: sudo apt-get install -y mongodb
      - run: 
          name: create user
          command: mongodb && mongo --eval 'db.createUser({ "user":"myrootuser", "pwd":"mypassword", "roles":[ { "role":"userAdminAnyDatabase", "db":"admin" } ] })'
      - python/install-packages:
          pkg-manager: pip
      - run: pip install pytest requests
      - run:
          name: Run tests
          command: python -m pytest
